# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'
platform :ios , '8.0'

target 'ContactsApp' do
    pod 'AFNetworking'
    pod 'GeoFire', '>= 1.1'
    pod 'MZFormSheetController'
end

